In [9]:
"""真の並列化"""

import numpy as np
import math

a = np.array([[1, 2, 3]]).T

b = np.random.rand(3, 10000)

b_ = [b[:, i:i+1] for i in range(b.shape[1])]

In [2]:
np.linalg.norm(a - b, axis=0)

array([2.55073596, 2.54075299, 2.62319055, ..., 2.9987572 , 2.56526081,
       2.46660235])

In [3]:
s = []
for bi in b_:
    s.append(np.linalg.norm(a - bi))

In [4]:
A = np.random.rand(3,3)
A @ b

array([[0.71850085, 1.01179311, 0.8483827 , ..., 0.8823057 , 1.12659774,
        0.81791251],
       [0.9671588 , 1.01119147, 1.03962139, ..., 0.70629416, 1.03415282,
        1.08484101],
       [0.85609401, 1.24351961, 1.05740948, ..., 1.10707572, 1.39218953,
        0.98986247]])

In [5]:
d = 3.2 - np.linalg.norm(a - b, axis=0)
d

array([0.64926404, 0.65924701, 0.57680945, ..., 0.2012428 , 0.63473919,
       0.73339765])

In [6]:
d > 0

array([ True,  True,  True, ...,  True,  True,  True])

In [7]:
np.where(d > 0)

(array([   0,    1,    2, ..., 9997, 9998, 9999]),)

In [8]:
t = np.where(d > 0)
t[0]

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [10]:
name = np
name2 = math

In [12]:
name.pi - name2.pi

0.0